### ISSUE TITLE
请问睡死问题能否解决

### ISSUE THREAD

**Issue by Xunflash** [amazingfate/armbian-xiaomi-elish#3]
在armbian官网刷入包后，屏幕经常睡死，息屏之后就无法再打开了，现在导致于都不太敢按电源键...请问有什么办法能够解决这个问题吗

**Comment by amazingfate** [comment]
禁用睡眠就行了

**Comment by Xunflash** [comment]
好的 感谢 还有一个问题就是目前官方键盘一直断联，请问这个有办法解决吗

**Comment by amazingfate** [comment]
键盘是已知问题，没有办法解决

**Comment by Xunflash** [comment]
> 禁用睡眠就行了

我在debian gnome这个版本里面关闭了 电源-自动挂起，但是我发现按电源键还是会导致黑屏无法再开启，只能再重启解决，请问具体要怎么设置呢

**Comment by amazingfate** [comment]
电源按钮行为可以设置为不处理，或者直接禁用掉systemd的睡眠功能

**Comment by Xunflash** [comment]
好的 我测试一下
