### ISSUE TITLE
高通865的开发板如何刷入

### ISSUE THREAD

**Issue by jackeyt** [amazingfate/armbian-xiaomi-elish#5]
大佬，如果是高通865的开发板如何刷入armbian?

**Comment by amazingfate** [comment]
参考elish的配置适配内核，其他的我也不太了解，没玩过开发板

**Comment by jackeyt** [comment]
开发板的也是基于edl，fastboot那一套，之前我是通过QFIL去刷入的：
![image](https://github.com/amazingfate/armbian-xiaomi-elish/assets/22190741/abd1a7de-0f92-403b-b505-db4014a2c88a)

就是不知道Armbian生成的，能否符合它的格式来烧录

**Comment by amazingfate** [comment]
armbian就一个boot.img和rootfs.img，需要提前给ufs分好区，在fastboot刷入

**Comment by jackeyt** [comment]
这里的boot.img只是kenel + dts，然后是通过什么命令让高通的edr或者fastboot去读取的？uboot的我知道是通过uboot的命令

**Comment by amazingfate** [comment]
这个boot.img是针对安卓设备的，用于刷入安卓的boot分区，abl可以直接加载。
