### ISSUE TITLE
大佬请教下，官方的standard support是这个项目吗，有没有怎么操作的文档

### ISSUE THREAD

**Issue by lucksufe** [amazingfate/armbian-xiaomi-elish#6]

**Comment by amazingfate** [comment]
刷机参考wiki的刷机文档：https://github.com/amazingfate/armbian-xiaomi-elish/wiki/Flashing-Guide
我最开始适配的是ubuntu jammy（22.04），但是现在armbian好像不提供下载了，可以实施noble或trixie
noble和trixe的qbootctl目前有bug，noble可以添加ppa解决：https://launchpad.net/~liujianfeng1994/+archive/ubuntu/qcom-mainline, trixie就只能等debian打包新版本了

**Comment by lucksufe** [comment]
感谢
