### ISSUE TITLE
屏幕无法点亮

### ISSUE THREAD

**Issue by h1kari-715** [amazingfate/armbian-xiaomi-elish#7]
**概述**
无论是使用您提供的unofficial镜像，还是官方的standard镜像，抑或是自行编译的内核和rootfs，全部都无法点亮屏幕（csot面板，但是也尝试过boe的镜像，有同样的问题。刷入过程均严格按照flashing-guide来进行）

**系统环境：**
ubuntu22.04.5 或 github-action ubuntu 22.04.5

**我所使用的编译命令：**
sudo ./compile.sh build \
                   BRANCH=current \
                   BUILD_DESKTOP=yes \
                   BUILD_MINIMAL=no \
                   DESKTOP_ENVIRONMENT=kde-plasma \
                   DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
                   KERNEL_CONFIGURE=no \
                   RELEASE=trixie \
                   BOARD=xiaomi-elish \
                   EXPERT=yes \
                   DESKTOP_APPGROUPS_SELECTED=no 

**具体表现：**
屏幕无法点亮。在小米logo显示完之后屏幕背光会亮~1s，之后屏幕彻底熄灭，且并没有与此具有相似问题线程的相似报错。https://github.com/armbian/build/pull/7359

**日志：**
[dmesg.txt](https://github.com/user-attachments/files/17964139/dmesg.txt)

**Comment by amazingfate** [comment]
Fixed by https://github.com/armbian/build/pull/7532

**Comment by h1kari-715** [comment]
经过测试，此问题确实已被修复。感谢您的工作。
